### PR TITLE
Resolve issue 83

### LINKED ISSUE #83: kable formatting for author lists
Missing a kable-ing function for author lists.

### PR DESCRIPTION
**Pull request by mariev**
closes #83 

Change summary:
- rename `vt_scrape_tags_from` to `scrape_tags_from` and make internal
- add public function `vt_scrape_function` for applying `scrape_tags_from` on functions
- add public function `vt_kable_function` to kable() output from ^^
- resolve warning around ghostscript/pdfcrop for test cases (scope creep to run tests)
- run `devtools::document()`

### CODE REVIEW

**Comment by mariev** [comment]
@thebioengineer what assumptions are we making for where R function documentation details are located? does `scrape_tags_from(type = "functions", ...)` address movement from `pkg_dir/R` to `pkg_dir/inst/validation/`?

**Comment by thebioengineer** [comment]
@mariev - yes, it looks at the source (pkg/R) when running normally, but when running on an installed package, it looks in the (validation) folder.

As for function name, could we use something more like `vt_scrape_authors()`? `vt_scrape_function()` makes me thing it is just for functions.

**Comment by mariev** [comment]
this *is* just for functions! there isn't an option to change the `type` passed to `scrape_tags_from`

**Comment by mariev** [comment]
per discussion with @thebioengineer today keeping `vt_scrape_tags_from` as public function, updates forthcoming

**Comment by mariev** [comment]
@thebioengineer ready for review - looks like all c.i. checks pass

**Review by thebioengineer — APPROVED** [review]

**Pull request merged**
