### PR TITLE
vt report username

### PR DESCRIPTION
**Pull request by thebioengineer**
- fix to `vt_use_report()` using the name as opposed to user name
- corrected path generation in ` vt_get_child_files()` - original review thought it would include the folders
- led to updating the format argument in kabling functions to use a new function - `vt_render_to()`, which determines the output type expected from `rmarkdown::render()` to correctly render the kables
- updated documentation
- adding requirements, test cases and test code authorship to report template & cleaned up and removed org specific pieces

### CODE REVIEW

**Review by mariev — COMMENTED** [review]
General comments: I think this PR is trying to do too much, which makes it time-consuming to match code up to stated goals/summary. Also overlaps PR #45.

-  re-writing `vt_get_child_files` assumptions again? we've flip-flopped on this a few times now 😬 😭
- what is the motivation for combining validation report author with other roles? This is inconsistent with {scharpnab}, {scharpbama} report structure.

**Comment by thebioengineer** [comment]
@mariev - I have separated out the kable changes (now #130), which were a large portion of the files changed. 

The changes to `vt_get_child_files()` and `vt_use_report()` are closely linked (due to validation_report.Rmd relying on it) - so I am leaving them tied together here.

**Comment by thebioengineer** [comment]
errors are due to needing #130 to be resolved

**Comment by thebioengineer** [comment]
@mariev  - develop merged in, all tests passing now

**Review by mariev — APPROVED** [review]
looks good!

I moved the updates to validation report template over to #45 and added another test

**Pull request merged**
