### PR TITLE
Peyman/shiny

### PR DESCRIPTION
**Pull request by peymaneshghi**
Added a dcf to bind vt_create_package() to RStudio's New Project Wizard.
Updated vt_use_req() to add an option to collect requirements through a shiny gadget. 
If we like this approach, same option can be added to vt_use_test_case().

### CODE REVIEW

**Comment by thebioengineer** [comment]
thanks for the PR @peymaneshghi - would you mind splitting out the features into two different PRs? that would make it simpler to play around and test them. I want to think around and play around with the shiny input features separately from adding in the wizard.

**Comment by peymaneshghi** [comment]
sure @thebioengineer, here I reverted the wizard commit and will open a separate new PR for that.
I hope this works for you or let me know if you prefer me to create a new branch and new PR for this one too?

**Comment by thebioengineer** [comment]
This works. Thanks @peymaneshghi . 

I was testing the dcf opening wizard, and I noticed that the same project gets opened twice when it is run. We will want to fix that.

**Comment by thebioengineer** [comment]
Will move above comment. 

Could you please add all the dependencies as @importFrom roxygen tags? I think I got all of them here:
```
#' @importFrom shiny textInput observeEvent reactiveValues paneViewer runGadget
#' @importFrom miniUI miniPage gadgetTitleBar miniContentPanel
#' @importFrom rhandsontable rHandsontableOutput renderRHandsontable hot_to_r
```

**Comment by peymaneshghi** [comment]
Thanks.. added those tags plus a few more

**Comment by peymaneshghi** [comment]
@thebioengineer and et.al., do you think this adds value to the package? if so I can work on test cases collection through shiny too.     
Equally you might prefer to keep the package lightweight and you may prefer not to add additional dependencies?

**Comment by thebioengineer** [comment]
I only had a short amount of time to play around with the shiny gadget - I think it makes it much more accessible to folks. I think it would be a good idea for us (you, myself, @mariev, @elimillera ) to brainstorm how we could use this concept and make it more flexible, and the best place for it to live (re: comment keeping package lightweight). This same gadget could be extended to most of the inputs, and if we could make it able to also edit the files, that would be pretty cool.

**Pull request closed without merging**
