### PR TITLE
code in use at SCHARP

### PR DESCRIPTION
**Pull request by mariev**
Draft PR to start compare & discussion differences between SCHARP & uat code

**SCHARP workflow**

- Input: expects a master .Rmd document (not included) with R chunks to format tables and import/scrape child docs in appropriate order. One child document for each:
    - Function specification
    - Process specification
    - Function test case
    - Process test case
    - Function test code
    - Process test code
- Output: single .pdf, ready for wet or electronic signatures

**Functions** (*Full documentation exists within this branch, this is a summary*)

- `signature_table`: creates LaTeX code from data.frame containing people name/titles/role, formatted for wet signature
- `scrape_news`: looks for version, `[version date]`, and `[validation]` info from NEWS file.
-  `dep_versions`: looks for package versions used in validation (when parent RMD is run) for packages listed in DESCRIPTION Imports
-  `scrape_coverage_block`: scrapes mapping of test cases ids to specification id, raw info lives in test case files
-  `scrape_function_specification_block`: pulls authorship info from specification and test case files, requires appropriate formatting of header
-  `scrape_test_code_block`: pulls authorship info from test code files, requires appropriate formatting of header
-  `scrape_function_author_block`: pulls authorship info from functions
- `scrape_spec_rmd`: pulls content (minus header) from .md and .Rmd files: specification and test case
- `eval_test_code`: evaluate and format reporter output from test code files

### CODE REVIEW

**Comment by mariev** [comment]
@htu @elimillera Not expecting that we will actually merge this branch as-is, but giving us a space to discuss the workflow expected by SCHARP legacy code. Happy to answer any questions and interested in how you think this fits with the uat code from Atorus.

**Comment by thebioengineer** [comment]
@elimillera - would you be able to do similarly to @mariev and summarize your functions? It would be great to go over duplicates and added functionality

**Comment by elimillera** [comment]
Definitely. Here are my thoughts below.

1.	`specs.csv` file is written containing the specifications, specifications IDs, and author information. This file is placed in ‘uat/input’.
2.	`test_cases.csv` is written containing the test cases, requirements tested for each test case, ID for each test/check, any output file, and authorship information. This file is placed in ‘uat/input’
3.	`test_cases.R` is written containing the test code written using test that. This file is actually run twice. The first portion is run to create and save an R object for testing traceability, just after the `is.null(vur)`. The second contains the actual test code, just after the `skip_if(is.null(vur))`. This allows us to only keep track of one file during the validation. When a user validates the script sources the test file which creates the `vur` and the Rdata the user might be checking, then after the user has entered their validation responses the second half runs the tests for the validation document.
4.	The user runs `uat_script_cals.R` which sources validation functions, creates the Rmds, creates the objects to test/validation, and opens a shiny interface for the users to enter their validation responses.
5.	The user submits their validation responses which runs the tests, stores the results, and knits the pdf.

The majority of our functions for scraping Rmds and evaluating tests codes are the pulled from the SCHARP process so there is quite a bit of overlap there. Here are the pieces that are different between them.
•	`make_test_case_rmd` - Writes the rmd from the test_cases.csv file.
•	`make_specification_rmd` - Writes the rmd from the specs.csv file.
•	A bit of functionality was written into the uat.Rmd. Main work in there is a function that writes a matrix for traceability between specs and test cases. It looks like it works similarly to your `generate_coverage_matrix` function but ours looks a little more clunky and relies on writing with a for loop.
It looks like there is quite a bit of overlap, but both of our workflows have good additions and the places where there is overlap is lifted from SCHARP. I really like the signature function, news functions, and packages versions. We should be able to create something that can be used to form a modular validation process/document. @thebioengineer @mariev what do you see as next steps? Are we waiting for the paper to get written to start working on this in ernist or did you want us to start working on integration and planning now?

**Comment by thebioengineer** [comment]
Thanks for the overview @elimillera. Thats good to know - My thoughts at this stage are to know what we have, and start the thought processes of how we want to organize things and less so on writing code since at this point we both have applied the code to our own workflows. Some things that @mariev mentioned that I think we can do without any code writing or having a finalized white paper are:
- families of functions. This can then lead to common prefixes
- ensuring documentation is up to snuff
- recording in issues known holes in the processes from our prior work. For example, someone opened some [issues on the original validation repo](https://github.com/thebioengineer/validation/issues) I have from RStudio::Conf.

@mariev - what are your thoughts on stuff prior to the WP being in a more formalized state?

**Comment by mariev** [comment]
@thebioengineer @elimillera thanks for moving this along. Grouping functions by activity, I am seeing the following cases:

A. Pulling data for tables e.g. R functions that generate a tbl_df/data.frame object:
- subset of news details
- signatures
- authorship details (need the flex to handle functions, requirements, test cases and test code - possible multiple functions) 
- requirement x test case coverage
- test code results

B. Creating .Rmd elements
- transforming .csv files
- transform informational tables from (A) into markdown code - possibly multiple functions
- collecting multiple RMD child elements into a single document.

C. Shiny App
- ui/server code to build app from requirements/test cases/test code files
- handler functions for interactivity 

D. Other infrastructure
- LaTeX style (SCHARP depends on VISCtemplates package)
- CSS
- RMD template

Some questions:
1. In a case where someone wants to start with csv for storing requirements/test cases/test code but bypass using a shiny app, is code structured so that they can directly transform the csv files to Rmd? Or is this something we need to add as a TODO?
2. What terminology should we be using for requirements/test cases/test code? I believe that SCHARP will be using "requirements" instead of "specifications" to better align with FDA guidance docs. And I see that there is some blurring of the nomenclature "test code" vs "test cases" in Eli's summary.
3. Auto numbering in Rmd files. Both necessary to cut down on rework for package maintainers and to be avoided from the perspective of being able to deprecate requirements/test cases/test code over time. Thoughts?

**Comment by mariev** [comment]
@elimillera I noticed that at R/pharma the {riskmetric} authors actually pulled the shiny app into a separate package. Do you have any thoughts on that delineation?

**Comment by elimillera** [comment]
@mariev I'm trying to think about all of these in terms <verb>_<noun> structure. What about something like `val_render_sig_table()`, `val_render_test_results()`, or `val_run_app()`?

Answers:
1. We have a function that transforms the csv to rmd before the shiny app runs, but its all built together at the end of the shiny app so that would be a todo.
2. I do use the terms "specification" and "requirement" interchangeably, I'm not sure what the exact terms are in our documents but I think "requirements" are better if that aligns with guidance. Test cases are the conditions that an application has to satisfy in words and test code is the actual R code that is used to test the programmatic parts.
3. The numbering and IDing was an unexpected challenge. We struggled to add in requirements and test cases because we had a logical order to them but there were times when we wanted to insert without renumbering all the items after it. I think this would be a really good addition.

From what I know the shiny app for the riskmetric application was more of an add-on to the riskmetric workflow instead of an extension of it. The app that was made has some database backend and support for package reviews on top of the quantitative output from riskmetric. I think it comes down to the workflow that was intended. The `pkg_ref` -> `pkg_assess` -> `pkg_score` workflow of riskmetric works well without an app, however we have a use case, manual validation tests, that would be difficult without a GUI.

**Comment by mariev** [comment]
I like the idea of starting all functions with `val_` for easy searching.

We could use some separation to tease out:
1. verbs to generate requirement/test case .Rmd files from input data e.g. csv or whatever future types we choose to implement
1. verbs to scrape from requirement/test case .Rmd/.md files into R data objects for including in summary tables, e.g. NEWS, coverage matrices
1. verbs to format R data objects for dropping into a validation report, e.g. `kable` + `kableExtra::` calls. 
1. verbs that leads to or facilitate interactivity
1. verbs that cause side effects e.g. runs test code, etc.
1. non-verbs for examples of infrastructure e.g. css, latex styles, validation report templates

Thinking that the first area {valtools} users may want to customize are (3) and (6)

**Comment by elimillera** [comment]
I really like those. I'm willing to bet is a good amount of functionality that will be put in the paper so I think its good to have buckets ready for how they will fit in to everything.

**Comment by mariev** [comment]
@elimillera @htu @thebioengineer captured our discussion regarding function naming conventions in the package wiki here: https://github.com/phuse-org/valtools/wiki/Function-naming-conventions

**Comment by thebioengineer** [comment]
I think we can close this - everything needed has been transformed

**Pull request closed without merging**
