### PR TITLE
Add hex and cheat sheet flow

### PR DESCRIPTION
**Pull request by thebioengineer**
- Adding the hex sticker developed by @mayagans and the cheatsheet by @mariev
- updating readme to show both

### CODE REVIEW

**Comment by elimillera** [comment]
@thebioengineer This might be a problem with just me but when I run `pkgdown::build_site` the cheatsheet isn't being rendered. My first guess is pkgdown doesn't know it needs it because it looks for stuff in a readme.rmd instead of the readme.md that we have but before I go too deep in that I just wanted to make sure this wasn't just an issue with my system.

Does the cheatsheet display for you in the pkgdown?

**Comment by thebioengineer** [comment]
Interesting. If I had to guess, that is because the path to the hex is not correctly being rendered in the local pkgdown build. If you look in the readme, the path is to the cheat sheet png is `inst/cheatsheets/valtools-chearsheet.png` - which I expect to get updated and resolved by github. The local builds don't do that. Not sure how we can preview a full github pages preview though.

**Comment by elimillera** [comment]
@thebioengineer So this is a little tricky apparently. For the regular readme it uses the root directory and the pkgdown uses the docs folder. Things in the pkgdown use references/figures and the readme uses man/figures. So links break between the readme and the pkgdown. We can still definitely display a picture, but I think we can actually link the picture to an external source. Something like this:
```
<a href="https://phuse-org.github.io/valtools/reference/figures/valtools-cheatsheet.pdf">
<img src="man/figures/valtools-cheatsheet.png" 
     alt="Cheatsheet on how to use the {valtools} R Package - functions & validation types" 
     style="width:50%;height:auto"/>
</a>
```
That way it works in both the pkgdown and the readme.

**Comment by thebioengineer** [comment]
I did a quick test - for images it updates the path from `man/figures/` to `references/figures`, so we should be okay to use that paradigm - I don't intend for these cheat sheets to be included in the builds (update `.Rbuildignore` to ignore paths of the cheatsheets folder within the package)

**Comment by thebioengineer** [comment]
R4.1.1 was released this morning per [Peter Dalgaard](https://twitter.com/pdalgd/status/1425010363251269633?ref_src=twsrc%5Etfw%7Ctwcamp%5Eembeddedtimeline%7Ctwterm%5Eprofile%3A_R_Foundation%7Ctwgr%5EeyJ0ZndfZXhwZXJpbWVudHNfY29va2llX2V4cGlyYXRpb24iOnsiYnVja2V0IjoxMjA5NjAwLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X2hvcml6b25fdHdlZXRfZW1iZWRfOTU1NSI6eyJidWNrZXQiOiJodGUiLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X3NwYWNlX2NhcmQiOnsiYnVja2V0Ijoib2ZmIiwidmVyc2lvbiI6bnVsbH19%7Ctwcon%5Etimelinechrome&ref_url=https%3A%2F%2Fwww.r-project.org%2F) - failures on windows "release" expected due to CRAN updates

**Review by mariev — APPROVED** [review]
@thebioengineer It looks like the latest checks were run via 4.1.0 - do we anticipate any changes necessary with the  move to 4.1.1 affecting this PR? if not I would move that work to a different issue.

otherwise looks great 👍

**Comment by thebioengineer** [comment]
@mariev - I don't anticipate any changes with 4.1.1 - that comment was that there was a failure in one of the actions due to failing to install pak, which I figured was due to changing "release" to 4.1.1 but not all CRAN builds were updated.

**Comment by thebioengineer** [comment]
Chatted with @elimillera this morning too, merging into dev.

**Pull request merged**
