### PR TITLE
Function Roxy Copy

### PR DESCRIPTION
**Pull request by thebioengineer**
Add/update code to facilitate copying roxygen comments from R functions into the validation output field

### CODE REVIEW

**Comment by thebioengineer** [comment]
It is happening at the time of build of the package. It needs to happen before the package is built otherwise that information is lost I think. Definitely if it is turned into a binary. This is to protect that.

**Comment by mariev** [comment]
can we add a test case to capture that?

**Comment by thebioengineer** [comment]
capture that the info is lost? or that it is saved even when in a binary?

**Comment by mariev** [comment]
When using `vt_validate_*`, we should be able to demonstrate that on building R authorship info is copied to correct location within /inst/.

**Comment by thebioengineer** [comment]
Ah, yes. I can do that!

**Review by elimillera — APPROVED** [review]

**Review by mariev — APPROVED** [review]
👍

**Pull request merged**
