### PR TITLE
Release 0.4.0

### PR DESCRIPTION
**Pull request by thebioengineer**
This marks release v0.4.0

Notable updates:
- Packet creation for validation external to packages with accompanying vignette
- new vignette on image snapshot comparisons
- bug fix to prevent file overwriting when running vt_use_* for a pre-existing file
- Cheat sheets
- Logo
- Improved test coverage

### CODE REVIEW

**Comment by mariev** [comment]
@thebioengineer can you look at #204 ?

**Comment by thebioengineer** [comment]
blocked by #210 - once merged in, this is GTG

**Review by mariev — CHANGES_REQUESTED** [review]
looks good! can we resolve #211 and pull in work from #210 as well?

**Comment by mariev** [comment]
closes #202

**Comment by thebioengineer** [comment]
@mariev - no problem. I'll ping once that is done

> looks good! can we resolve #211 and pull in work from #210 as well?

**Comment by thebioengineer** [comment]
resolved #211 - @mariev , please approve once the tests pass

**Review by mariev — APPROVED** [review]

**Pull request merged**
