### PR TITLE
Get function author details

### PR DESCRIPTION
**Pull request by mariev**
Code to scrape the R documentation block for authorship details. Some assumptions about documentation structure:

- Author is tagged via '@section Last updated by:'
- Date is tagged via `@section Last updated date:'
- Skips scraping roxygen blocks without ☝️ tags
- Namespace tags `@export` or `@keyword internal` does not block from scraping
- If dummy roxygen block is used, identifies "function name" from `@name` tag.
- allows for flexibility in date - ymd or mdy (note there was [a comment](https://github.com/thebioengineer/validation/issues/6) that this flexibility should not be required due to SOP/GDP, but adding it so that the function may be used across orgs with different standards)

### CODE REVIEW

**Comment by thebioengineer** [comment]
This might be a little harebrained, but would we want to maybe look at defining our own roxygen tags at this point? I know we discounted that in 2019, but maybe we could revisit and simplify effort for ourselves?

**Comment by thebioengineer** [comment]
roxygen documentation was pretty nice: https://roxygen2.r-lib.org/articles/extending.html

if we wanted to use the tags `@lastUpdateBy` and `@lastUpdateDate`:
```
#' @export
roxy_tag_parse.roxy_tag_lastUpdateBy <- function(x) {
  roxygen2::tag_markdown(x)
}

#' @export
roxy_tag_parse.roxy_tag_lastUpdateDate <- function(x) {
  x$val <- as.character(lubridate::date(x$raw))
  x
}

#' @export
roxy_tag_rd.roxy_tag_lastUpdateBy <- function(x, base_path, env) {
  rd_section("lastUpdateBy", x$val)
}

#' @export
roxy_tag_rd.roxy_tag_lastUpdateDate <- function(x, base_path, env) {
  rd_section("lastUpdateDate", x$val)
}

#' @export
format.rd_section_lastUpdateBy <- function(x, ...) {
  paste0(
    "\\section{Last Update By:}{\n", x$value, "\n}\n"
  )
}

#' @export
format.rd_section_lastUpdateDate <- function(x, ...) {
  paste0(
    "\\section{Last Update Date:}{\n", x$value, "\n}\n"
  )
}

```

we could also consider having a single `@validation` tag? formatted as newline author newline date?

**Comment by mariev** [comment]
I think we discounted in 2019 due to time constraints. If we add now, I think it may be helpful to keep current functionality but _add_ the option for the new tags, for backwards compatibility

**Comment by mariev** [comment]
putting this PR on pause until we can address #16

**Comment by thebioengineer** [comment]
Hey @mariev - do we want to look at a more generic approach to the roxygen tags than manually scraping them every time? I [opened a branch](https://github.com/phuse-org/valtools/blob/parse_roxygen_generics/R/parse_roxygen.R) this weekend to investigate some thoughts - Mainly thinking about how to set up a more generic method to dealing with different input types. I think it might help with extensibility (to csv's for example).

**Comment by mariev** [comment]
How will this play with dynamic references? It looks like the `parse_roxygen` generic is making some assumptions based on the file type but should probably be a way to handle the md code returned via `dynamic_reference_rendering(INPUT_FILE)`.

**Comment by thebioengineer** [comment]
We can definitely do that. Since that isn't available in develop, and we are still figuring out how we will implement it, I was going to wait to add that in

**Comment by mariev** [comment]
deprecating this due to work in #38

**Pull request closed without merging**
