### PR TITLE
Validation packets

### PR DESCRIPTION
**Pull request by thebioengineer**
- Adds a function to explicitly support the validation process to "external software"
- Adds template for packet that trims expectation of function authors
- Adds vignette for the process of validation external to a package

### CODE REVIEW

**Comment by thebioengineer** [comment]
on review of the hex behavior. maybe we move the cheat sheet into `man/figures`?

**Review by mariev — COMMENTED** [review]
How confusing is it to switch between adding validation to an existing package vs creating a standalone validation packet? I am thinking of the use case where a package may have be lurking in an unvalidated state for a while and ppl want to add validation without disrupting existing dev work. 

It looks like we can initiate validation one of three ways:
- `vt_create_packet`
- `vt_create_package`
- `vt_use_validation`

imo,  "create" is when the validation framework is initiated, so why the presence of "use" ?

**Comment by thebioengineer** [comment]
I see vt_use_validation as adding validation infrastructure to existing packages or existing folders. create makes the project or package with the infrastructure existing (Calls use under the hood)

**Comment by mariev** [comment]
I agree, there is a nuanced difference between starting a project w/ validation in mind vs adding validation post-hoc. I am wondering if {valtools} needs to name that difference or we can present the different use cases as equally valid approaches to starting validation? What is the value-add for the users to split creating a packet (adds validation framework to a designated location) vs adding validation to an existing package (adds validation framework to a designated location)? And how do we make that value-add immediately obvious?

**Comment by thebioengineer** [comment]
Part of it is also for separation of function purposes - so we can share the logic of creating the validation infrastructure (via vt_use_validation) to concepts existing in usethis::create_

**Review by mariev — APPROVED** [review]
added to the latest valtools cheatsheet draft.

**Pull request merged**
